### ISSUE TITLE
[WIP] Chatterbot v2.0

### ISSUE THREAD

**Issue by neel-j-dev** [OpiusOP/issues#11]
- [x]  Set up Chatter bot API using pypi and local installs
- [x] Create custom trainers for:
- [x] Chatterbot english corpus
- [x] NLTK corpus
- [x] Find a way to read stdin and stdout from python files using JS
- [ ] Set up preprocessing framework to use logged messages
- [x] GPU acceleration for training

Commands
-------------

- [ ] `!train` - Bot will be trained on startup, if training score is low, this command will retrain
- [x] Tagging opius should be the command for asking it something

**Comment by Edsardio** [comment]
@XzibitGG Can this issue be closed?
