### ISSUE TITLE
Social

### ISSUE THREAD

**Issue by Edsardio** [OpiusOP/issues#14]
Description
-------------
Should post the socials of Opium Pulses Ltd.

```
If you want to stay in contact with us:
Homepage: <http://www.opiumpulses.com/>
Twitch: <http://www.twitch.tv/OpiumPulses>
YouTube: <http://www.youtube.com/OpiumPulses>
Twitter: <https://twitter.com/OpiumPulses>
Facebook: <https://www.facebook.com/OpiumPulses>
Podcast: <http://podcast.opiumpulses.com/>
```

Checklist
-------------
- [x] Command created (!social)
- [x] Command tested
- [x] Any found bugs fixed

**Comment by SlipSlot** [comment]
Remove podcast from the list, this is now integrated into the website.
