### ISSUE TITLE
Giveaways

### ISSUE THREAD

**Issue by Edsardio** [OpiusOP/issues#17]
Description
-------------
Should post a link to the giveaways

```
We do the giveaways spontaniously and don't do it on a weekly/monthly basis for example. We do it when we have the games available and announce it as soon as we can.
Opium Pulses Giveaways: <http://www.opiumpulses.com/giveaways>
Member giveaways: <http://steamcommunity.com/groups/OpiumPulsesGiveaways/discussions/2/>
```

Checklist
-------------
- [x] Command created (!giveaways)
- [x] Command tested
- [x] Any found bugs fixed

**Comment by SlipSlot** [comment]
Please change to:

Giveaways are added to the website on a regular basis and are sourced from sales, bundles and direct from developers: url
