### ISSUE TITLE
Profanity Command

### ISSUE THREAD

**Issue by neel-j-dev** [OpiusOP/issues#2]
Usage
------
`!profanity [ + | add]  [word | phrase]` - Adds the word or phrase to the guild's profanity DB table
`!profanity [ - | remove]  [word | phrase]` - Remove the word or phrase to the guild's profanity DB table

MessageManager
-------------------
Loads all files in `./Messages` which contains all functions that need to be run when a message is received 

-------
If message contains words in guild's profanity list, message will be deleted and author will be warned in DMs.

**Comment by Edsardio** [comment]
Resolved
